<a href="https://colab.research.google.com/github/pgideon1/NumPy-Project/blob/main/NumPy_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Importing Dataset

In [1]:
import numpy as np


### reading dataset

In [3]:
data = np.genfromtxt('/content/KAG_Conversion_Data.csv',delimiter = ",",skip_header=1)
print(data)

[[7.08746000e+05 9.16000000e+02 1.03916000e+05 ... 1.42999995e+00
  2.00000000e+00 1.00000000e+00]
 [7.08749000e+05 9.16000000e+02 1.03917000e+05 ... 1.82000002e+00
  2.00000000e+00 0.00000000e+00]
 [7.08771000e+05 9.16000000e+02 1.03920000e+05 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 ...
 [1.31441200e+06 1.17800000e+03 1.79979000e+05 ... 4.02899995e+01
  2.00000000e+00 0.00000000e+00]
 [1.31441400e+06 1.17800000e+03 1.79981000e+05 ... 1.98710001e+02
  8.00000000e+00 2.00000000e+00]
 [1.31441500e+06 1.17800000e+03 1.79982000e+05 ... 1.65609999e+02
  5.00000000e+00 2.00000000e+00]]


In [5]:
data.shape

(1143, 11)

### How many unique ad campaigns (xyzcampaignid) does this data contain ? And for how many times was each campaign run ?

In [6]:
xyzcampaignid = np.array(data[:,1])
xyzcampaignid

array([ 916.,  916.,  916., ..., 1178., 1178., 1178.])

In [7]:
print(np.unique(xyzcampaignid))

[ 916.  936. 1178.]


In [9]:
count = xyzcampaignid[xyzcampaignid==916.].shape[0]
print(count)

54


In [10]:
count = xyzcampaignid[xyzcampaignid==936.].shape[0]
print(count)

464


In [11]:
count = xyzcampaignid[xyzcampaignid==1178.].shape[0]
print(count)

625


In [18]:
age = np.array(data[:,3])
age

array(['30-34', '30-34', '30-34', ..., '45-49', '45-49', '45-49'],
      dtype='<U11')

In [20]:
print(np.unique(age))

['30-34' '35-39' '40-44' '45-49']


In [4]:
ad = np.array(data[:,8])
ad

array([  1.42999995,   1.82000002,   0.        , ...,  40.28999949,
       198.7100005 , 165.6099987 ])

In [5]:
ad_min = np.min(ad)
ad_min

0.0

In [7]:
ad_max = np.max(ad)
ad_max

639.9499981

In [9]:
ad_mean = np.mean(ad)
ad_mean

51.36065613141295

In [11]:
id = np.array(data[:,7])
id

array([  1.,   2.,   0., ...,  28., 135., 114.])

In [12]:
id_max = np.max(id)
id_max

421.0

In [13]:
max_click = np.max(data[:,7])
max_click

421.0

In [14]:
b = np.where((data[:,7])==max_click) 

In [16]:
ad_id_max=data[b,0]
ad_id_max

array([[1121814.]])

In [17]:
ad_con = data[:,10]
ad_con

array([1., 0., 0., ..., 0., 2., 2.])

In [20]:
sum_amount = sum(ad_con)
sum_amount

1079.0

In [21]:
max_amount = max(ad_con)
max_amount

21.0

In [23]:
ad_con[data[:,7]==421]

array([13.])